server:
  port: 9966
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
spring:
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.99.99:6612/blob?useUnicode=true&characterEncoding=UTF-8&serverTimeZone=UTC
  data:
    redis:
      host: 192.168.99.99
      port: 6379
      password: fjl1020
      database: 11
sc-blob:
  jwt:
    expiration: 604800000
    salt: 'FangJiaLeSecretKeyFangJiaLeSecretKeyFangJiaLeSecretKeyFangJiaLeSecretKey'
  minio:
    endpoint: http://192.168.99.99:9000
    accessKey: minioadmin
    secretKey: minioadmin
    bucketName: blob-bucket